type = Quantifier
name = Test
analysis_type = QUINT
quantifier_input_dir = Z:/HBP_Analytics/PyNutil/PyNutil_testing/Example1_nonlinear_allen_mouse/segmentations
quantifier_atlas_dir = Z:/HBP_Analytics/PyNutil/PyNutil_testing/Example1_nonlinear_allen_mouse/atlasmaps
label_file = Allen Mouse Brain 2017
custom_label_file = 
xml_anchor_file = Z:/HBP_Analytics/PyNutil/PyNutil_testing/Example1_nonlinear_allen_mouse/alignment.json
quantifier_output_dir = Z:/HBP_Analytics/PyNutil/PyNutil_testing/Example1_nonlinear_allen_mouse/output_nutil_v1_0_5
output_report = All
extraction_color = 0,0,0,255
object_splitting = Yes
object_min_size = 1
global_pixel_scale = 1
quantifier_pixel_scale_unit = pixels
use_custom_masks = No
custom_mask_directory = 
custom_mask_color = 255,255,255,255
output_report_type = CSV
custom_region_type = Default
custom_region_file = 
coordinate_extraction = All
coordinate_single_point = No
pixel_density = 1
display_label_id = No
output_region_id = Yes
pattern_match = _sXXX
files = 
nutil_version = v1.0.5
nutil_version = v1.0.5
nutil_version = v1.0.5
